---
- name: Debian family
  command: echo Debian family

- name: Add universe repository into sources list
  apt_repository:
    repo: deb http://us.archive.ubuntu.com/ubuntu xenial main universe
    state: present

- name: Install figlet
  apt:
    state: present
    name: figlet
    update_cache: yes

- name: Dump figlet output into motd
  become: true
  shell:  figlet '{{ host }}' > /etc/motd

