---
- name: Redhat family
  command: echo Redhat family  

- name: Install figlet
  become: true
  yum:
    state: present
    name: figlet

- name: Dump figlet output into motd
  become: true
  shell:  figlet '{{ host }}' > /etc/motd

